
  CREATE TABLE "MEMBER" 
   (	"ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"PW" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TEL" VARCHAR2(13 BYTE) NOT NULL ENABLE, 
	"NICKNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"GENDER" CHAR(3 BYTE) NOT NULL ENABLE, 
	"REGION" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"BIRTH" DATE NOT NULL ENABLE, 
	"CDATE" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"UDATE" TIMESTAMP (6), 
	"PIC" BLOB, 
	"COL1" VARCHAR2(30 BYTE), 
	"COL2" VARCHAR2(30 BYTE), 
	"COL3" VARCHAR2(30 BYTE), 
	 CONSTRAINT "MEMBER_CHK1" CHECK (gender in ('남','여')) ENABLE, 
	 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
   ) ;
 

   COMMENT ON COLUMN "MEMBER"."ID" IS '아이디(메일)';
 
   COMMENT ON COLUMN "MEMBER"."PW" IS '비밀번호';
 
   COMMENT ON COLUMN "MEMBER"."TEL" IS '전화번호';
 
   COMMENT ON COLUMN "MEMBER"."NICKNAME" IS '별칭';
 
   COMMENT ON COLUMN "MEMBER"."GENDER" IS '성별(''남'',''여'')';
 
   COMMENT ON COLUMN "MEMBER"."REGION" IS '지역';
 
   COMMENT ON COLUMN "MEMBER"."BIRTH" IS '생년월일(''yyyymmdd'')';
 
   COMMENT ON COLUMN "MEMBER"."CDATE" IS '생성일';
 
   COMMENT ON COLUMN "MEMBER"."UDATE" IS '변경일';
 
   COMMENT ON COLUMN "MEMBER"."PIC" IS '사진(확장자 jpg,gif,png)';
 
   COMMENT ON COLUMN "MEMBER"."COL1" IS '임시1';
 
   COMMENT ON COLUMN "MEMBER"."COL2" IS '임시2';
 
   COMMENT ON COLUMN "MEMBER"."COL3" IS '임시3';
 
